color:
  saturation: 0.3136327
  brandStrength: 0.2518797
  rhythmicContrast: 0.8720496
  brandColors:
    - '#014DAB'
    - '#A3A3B4'
    - '#66636F'
    - '#E1E1DF'
    - '#181F39'
  lightness: 0.8937125
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
typography_spectrum: 0.1928034
name: Trystan Trenberth
